site_name: "ACC-UB User Guide"
site_description: 'User guide for the Advanced Computing Center'
site_author: 'ACC-UB system administrators'
docs_dir: docs/
repo_url: 'https://github.com/UniBuc-DTD/advanced-computing-center-user-guide'
edit_uri: 'edit/main/docs'
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - HPC cluster: hpc.md
  - SLURM guide: slurm.md
  - Virtual machines platform: hci.md
  - Storage: storage.md
  - Network: network.md
  - VPN access: vpn.md
  - Acknowledgement: acknowledgement.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
