name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - static-site-generation

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Deploy docs
        uses: UniBuc-DTD/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
