name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - static-site-generation

jobs:
  build_and_deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install .

      - name: Build docs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
